### ISSUE TITLE
SemshiTextChanged Error when enter completion from compe-nvim in nvim 0.5?

### ISSUE THREAD

**Issue by lkhphuc** [numirias/semshi#105]
I recently upgrade to nvim nightly 0.5 and using compe-nvim for completion.
Semshi highlighting is working fine however it throws this error every time I press enter to accept completion from compe-nvim? 
```
error caught in async handler '/Users/phuc/.local/share/nvim/site/pack/packer/start/semshi/rplugin/python3/semshi:function:SemshiTextChanged [[]]'                                         
Traceback (most recent call last):
  File "/Users/phuc/.local/share/nvim/site/pack/packer/start/semshi/rplugin/python3/semshi/plugin.py", line 108, in event_text_changed
    self._cur_handler.update()
AttributeError: 'NoneType' object has no attribute 'update'
```

Does anyone know why? Thanks.

**Comment by alexcg1** [comment]
I'm facing the same issue. Did you ever get it fixed?

**Comment by alexcg1** [comment]
It works okay if you put
```vim
inoremap <silent><expr> <C-Space> compe#complete()
inoremap <silent><expr> <CR>      compe#confirm('<CR>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
inoremap <silent><expr> <C-f>     compe#scroll({ 'delta': +4 })
inoremap <silent><expr> <C-d>     compe#scroll({ 'delta': -4 })
```

In your `~/.config/nvim/init.vim`

**Comment by lkhphuc** [comment]
No, I'm disabling Semshi for now.

**Comment by alexcg1** [comment]
Likewise. It's a real shame, they're both really nice plugins

**Comment by JonsSpaghetti** [comment]
Happens using coc as well, seems like it might be any completion plugin.

**Comment by sh8** [comment]
The same thing is happening to me....

**Comment by sh8** [comment]
https://github.com/numirias/semshi/pull/106
This PR would fix this problem!

**Comment by solomonxie** [comment]
Seems the CI has failed... 😭

**Comment by sh8** [comment]
Yes, the old CI settings seem to be broken. @numirias stopped maintaining this repo a year ago, so the fastest way to fix this issue is to use [my forked one](https://github.com/sh8/semshi).

**Comment by solomonxie** [comment]
Yes that’s exactly what I did for a quick fix, lol. Thanks for the fix anyway, great work appreciate it.

**Comment by blueyed** [comment]
Note that this could also be fixed upstream maybe, e.g. with jedi-vim I've fixed it like this: https://github.com/davidhalter/jedi-vim/pull/652/commits/e38372ffa2ff64713f62ae233c4be01cf13cca43 (in a WIP branch/feature, but still).

**Comment by numirias** [comment]
Folks, I really appreciate all your work while I had to pause maintenance. I understand there are important PRs to merge and bugs to fix.

I'm alive and will tackle the pile of issues in the next days. Also, I'm looking forward to implementing some major enhancements.

**Comment by wookayin** [comment]
@numirias Thanks and I'm happy to hear that you are alive. Merging quickfixes like #106 in the meantime would be greatly appreciated.

**Comment by alexcg1** [comment]
That's awesome to hear @numirias , welcome back!

**Comment by lkhphuc** [comment]
#106  merged so close this issue and wait for major enhancements.
