### ISSUE TITLE
Disable reparsing in insert mode

### ISSUE THREAD

**Issue by yevhen-m** [numirias/semshi#13]
How to disable reparsing in insert mode?

I've tried 
```
    autocmd InsertEnter *.py Semshi disable
    autocmd InsertLeave *.py Semshi enable
```
but this disables syntax completely, all I want is to stop parsing till I get to normal mode.

**Comment by numirias** [comment]
Yep, `disable` also clears all highlights. I'll implement a command to just pause reparsing.

(As an aside, is there a particular reason you want to pause parsing during insert mode (e.g. performance)? In that case, you may also want to play around with `g:semshi#update_delay_factor`.)

**Comment by yevhen-m** [comment]
Yes, cursor just lags when I type.

**Comment by yevhen-m** [comment]
@numirias I don't need instant reparsing in insert mode and I'd like typing to be as smooth as possible no matter how many lines a module has. That's why I think disabling it in insert mode can solve the issue.

**Comment by numirias** [comment]
@yevhen-m The lagging is unfortunate. Even in large files, the cursor shouldn't lag. The parsing is done in a separate thread. Are you using neovim on the terminal or a particular frontend?

FWIW, you can now do:

```VimL
    autocmd InsertEnter *.py Semshi pause
    autocmd InsertLeave *.py Semshi enable
```

**Comment by yevhen-m** [comment]
I see a lag between the moment I type a letter and this letter is underlined and I don't like this. It looks like this is cause by delayed highlight updates. Cursor is not blocked. And it seems to me that this is a valid scenario, but I simply don't like it ;).
