### ISSUE TITLE
Syntax not same as yours.

### ISSUE THREAD

**Issue by orachimary** [numirias/semshi#39]
Hi. 
I'm was followed instructions exactly and installed all stuff. But my syntax highlighting looks ugly.
![pict](https://user-images.githubusercontent.com/18115830/58365551-92f75400-7edf-11e9-9d62-35972b8202fc.PNG)
I use:
`GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
and
Ubuntu 18.04.2 LTS`
Can you give guidance what need to do that it look as yours?

**Comment by numirias** [comment]
Semshi only colorizes some of your syntax elements, the rest (e.g. strings and keywords) is determined by your configured colorscheme. That means, Semshi is responsible for making `csv` orange, but not for making `import` brown as in your example.

You can choose colorschemes from e.g. [here](https://github.com/rafi/awesome-vim-colorschemes). The one that comes the closest to the readme examples is probably `molokai`.

If you want to change Semshi scope colors, there are [instructions in the readme](https://github.com/numirias/semshi#highlights).
