### ISSUE TITLE
cursor word highlight error

### ISSUE THREAD

**Issue by pysnow530** [numirias/semshi#42]
![image](https://user-images.githubusercontent.com/9863744/59204140-99b9e280-8bd2-11e9-9c62-94957f6d987d.png)

**Comment by pysnow530** [comment]
I find `∗` is unicode and it is not `*`. Maybe this is an multibyte error.

**Comment by numirias** [comment]
Thanks for reporting!
Your screenshot screenshot indicates there is also a syntax error. As long as the syntax is incorrect, the parser can not correctly determine the location of names in the source code, and you will find bad offsets or misplaced highlights. Does the bug still reproduce after you have fixed the error?

**Comment by pysnow530** [comment]
After fixed the error, all is fine.

It's a wonderful plugin, thank you so much.
