### ISSUE TITLE
Jumps on input

### ISSUE THREAD

**Issue by thomasballinger** [numirias/semshi#56]
I get some jumpy behavior when I edit text and have a syntax error as it disappears and reappears. Do other folks see this? Should I be trying to disable other plugins to look for interactions? I'm using `let g:deoplete#auto_complete_delay = 100`.
![jumps](https://user-images.githubusercontent.com/458879/68561216-72717680-03f9-11ea-967b-9f70b66f9abf.gif)

**Comment by numirias** [comment]
Do you mean the appearance and disappearance of the sign column? In that case, would `set signcolumn=yes` to permanently show the sign column be an option for you?

**Comment by thomasballinger** [comment]
Ah thank you! I should have read through the docs, hopefully this post helps others now.

Vim jittering on error check, sign column momentarily leaving, errors disappear and reappear quickly
