### ISSUE TITLE
Unkown function: SemshiBufWipeout when closing windows

### ISSUE THREAD

**Issue by jdhao** [numirias/semshi#59]
Hi, when I close windows, for example, after updating plugins using `PlugUpdate` command provided by vim-plug, I saw the following errors:

```
Error detected while processing BufWipeout Autocommands for "*":
E117: Unknown function: SemshiBufWipeout
E117: Unknown function: SemshiBufWipeout
E117: Unknown function: SemshiBufWipeout
```

This happens after I update to the latest version of semshi.

**Comment by numirias** [comment]
Did you do `:UpdateRemotePlugins`?

**Comment by jdhao** [comment]
After using `:UpdateRemotePlugins`, it seems that the issue is gone. This is a little weird because I have set up the post-update hooks for this plugin. The `:UpdateRemotePlugins` command should be run automatically on each installation or update.

**Comment by jdhao** [comment]
Maybe it is because I have added the `'for': 'python'` part so that the `:UpdateRemotePlugins` command will not be run automatically?

**Comment by numirias** [comment]
@jdhao TBH, I never got automatic `UpdateRemotePlugins` to work myself. I don't think it's due to something within this plugin, though.

**Comment by jdhao** [comment]
I also use deoplete and set up the post-update hook, and it works great:

```
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
```

Maybe I should file an issue in vim-plug repo. Thanks for your answer!

**Comment by jdhao** [comment]
It seems that `for` option should not be used. Otherwise, command provided by semshi seems not to be loaded. Ref: https://github.com/junegunn/vim-plug/issues/593#issuecomment-279142403

**Comment by numirias** [comment]
Weird, in my config I'm not using `for:`

**Comment by jdhao** [comment]
My minimal working init.vim is as follows:

```
if has('win32')
    let s:PLUGIN_HOME=expand('~/AppData/Local/nvim/plugged')
else
    let s:PLUGIN_HOME=expand('~/.local/share/nvim/plugged')
endif

call plug#begin(s:PLUGIN_HOME)
Plug 'numirias/semshi', { 'do': ':UpdateRemotePlugins' }
call plug#end()
```

**Comment by numirias** [comment]
Thanks, not sure why it doesn't work for me. Closing the issue now since it doesn't seem related to Semshi

**Comment by intramuros** [comment]
Hi, I have the same issue and this error:
``` Error detected while processing BufWipeout Autocommands for "*":
E117: Unknown function: SemshiBufWipeout
```
appears even after deleting semshi plugin.

**Comment by numirias** [comment]
@intramuros You need to run `:UpdateRemotePlugins`.

**Comment by AucaCoyan** [comment]
Sorry, I ran `:UpdateRemotePlugins` and I received this, is this ok?
```
function remote#host#UpdateRemotePlugins[6]..<SNR>92_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require[13]..provider#Poll, line 4
Vim(if):Error invoking 'poll' on channel 6:^@ch 6 was closed by the client
function remote#host#UpdateRemotePlugins[6]..<SNR>92_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require[13]..provider#Poll, line 14
Failed to load python3 host. You can try to see what happened by starting nvim with
$NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr
is available in messages.
remote/host: generated rplugin manifest: C:\Users\aucac\AppData\Local\nvim-data/rplugin.vim
Press ENTER or type command to continue
```

**Comment by wookayin** [comment]
If you see such errors

> Failed to load python3 host. You can try to see what happened by starting nvim with

You need to configure `g:python3_host_prog` properly in your init.vim config and install `pynvim` there:
```bash
python3 -m pip install --upgrade --force-reinstall pynvim
```
and make sure python3 host works OK:
```vim
:echo py3eval("sys.version_info")
```

and then `:UpdateRemotePlugins` again.

**Comment by AucaCoyan** [comment]
Thank you @wookayin !
