### ISSUE TITLE
E117: Unknown function: SemshiBufWipeout

### ISSUE THREAD

**Issue by newtorn** [numirias/semshi#60]
After I PluginInstall each time, key press q to quit, I will get a message from neovim:
Processing BufWipeout autocmd "*" occurs error:
E117: Unknown function: SemshiBufWipeout

Work on Darwin, Neovim:
NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5

vim-plug:
Plug 'numirias/semshi', { 'do': ':UpdateRemotePlugins', 'for' :['python', 'vim-plug'] }

**Comment by numirias** [comment]
Duplicate of #59

**Comment by wookayin** [comment]
The solution is to run `:UpdateRemotePlugins`, but this error can still happen often (e.g. running `vim-plug` installation or for some reason rplugin gets broken). [My fork of semshi](https://github.com/wookayin/semshi/issues/1) fixes it: https://github.com/wookayin/semshi/commit/52df970d21dcc1976b3842179afe17fbc9344bcf .
