### ISSUE TITLE
Unknown function: SemshiBufWipeout

### ISSUE THREAD

**Issue by robertocarta** [numirias/semshi#61]
Hi, after a PlugUpdate I'm getting the following when opening python files. I had to remove the plugin to keep working. 
![image](https://user-images.githubusercontent.com/15035783/70318289-fe6f9600-181f-11ea-8cad-e667e7394488.png)

**Comment by lithammer** [comment]
Run `:UpdateRemotePlugins` again.

**Comment by shubgant** [comment]
Had the same problem, then realised I was opening files with vim instead of neovim, maybe that was the problem?
