### ISSUE TITLE
How to change the default red highlight

### ISSUE THREAD

**Issue by dky** [numirias/semshi#63]
Hello, Thank you for your work on this, it's useful. I'm struggling to figure out how to change the red highting when you select or hover over a var. I think it's a bit obtrusive and want to make it more subtile. Thing is I don't know which of the params controls this:

function MyCustomHighlights()
    hi semshiImported      ctermfg=red
endfunction
autocmd FileType python call MyCustomHighlights()

Any ideas on how to tweak this?

Thanks!

**Comment by numirias** [comment]
Do you mean `semshiSelected`?

As in:
```VimL
hi semshiSelected        ctermfg=231 guifg=#ffffff ctermbg=161 guibg=#d7005f
```

**Comment by dky** [comment]
Yes! This did it, Default hight light color can now be altered. Thanks for the help!
