### ISSUE TITLE
Commented code always highlighted

### ISSUE THREAD

**Issue by marcociccone** [numirias/semshi#71]
Hi, 
it appears that by default the commented code is always highlighted. 
How can I turn it off? 
Thanks!

![image](https://user-images.githubusercontent.com/1114692/76528222-bf7d5c00-6470-11ea-8dda-6b279334ccda.png)

**Comment by wookayin** [comment]
Without semshi does it look fine? What does `hl Comment` read?

**Comment by marcociccone** [comment]
Sorry I've wrongly attributed this behaviour to semshi. 
It was a tmux related problem actually!
