### ISSUE TITLE
How to uninstall/clean reinstall semshi?

### ISSUE THREAD

**Issue by tbrodbeck** [numirias/semshi#76]
Hi! 
I changed my username on macOS. Now I get error messages when using semshi like this:
```
Error detected while processing function remote#define#request:
line    2:
Error invoking '/Users/OLDUSERNAME/.config/nvim/plugged/semshi/rplugin/python3/semshi:
autocmd:BufEnter:*.py' on channel 8 (python3-rplugin-host):
no request handler registered for "/Users/OLDUSERNAME/.config/nvim/plugged/semshi/rplu
gin/python3/semshi:autocmd:BufEnter:*.py"
Press ENTER or type command to continue
```
And in nvim I get the error message:
```
no notification handler registered for "/Users/OLDUSERNAME/.config/nvim/plugged/semshi/rplugin/python3/semshi:autocmd:CursorMoved:*.py"
Press ENTER or type command to continue
```
Now I would like to uninstall semshi to reinstall it cleanly (to make it know my new username)
But uncommenting and using `:PlugClean` does not seem to be enough. (the directory is deleted) But I still get the error.
I even renamed my whole nvim folder in .config, I tried reinstalling pynvim and, additionally, nvim itself and it did not help it.

Maybe you can tell me a way how to uninstall semshi cleanly?

**Comment by wookayin** [comment]
`rm -rf ~/.vim/plugged/semshi`

**Comment by numirias** [comment]
You need to run `:UpdateRemotePlugins`. If you just remove the plugin files, neovim still tries to find handlers from your generated remote plugin manifest.

**Comment by tbrodbeck** [comment]
> `rm -rf ~/.vim/plugged/semshi`
> 
> `vim +PlugInstall`
I am using nvim not vim, but thanks for the answer :)

Actually `:UpdateRemotePlugins` did fix it. Thanks nurmirias! 
I love your plugin!
