### ISSUE TITLE
Semshi stopped highlighting mysteriously - how to debug?

### ISSUE THREAD

**Issue by butla** [numirias/semshi#79]
Hey, Semshi stopped working for me today. No highlighting is happening. I updated all my plugins, my NeoVim is 0.4.3, I do UpdateRemotePlugins, when I source `~/.local/share/nvim/rplugin.vim` (I thought that might not getting loaded somehow) it tells me that semshi is already loaded. `:Semshi` tells me "this is Semshi". `:Semshi enable` and `:Semshi highlight` don't do anything.

Do you have any pointers on how to debug what's happening?

**Comment by butla** [comment]
As mysteriously as it started, it stopped and things are working again, so I'll close the issue. But I still think it would be nice to get some pointers on debugging.

**Comment by a-elhag** [comment]
Same thing happens to me all the time, it just randomly stops working
