### ISSUE TITLE
Wierd coloring bug

### ISSUE THREAD

**Issue by InCogNiTo124** [numirias/semshi#81]
This is from my lab asignment for uni course:
![Screenshot_20200604_000443](https://user-images.githubusercontent.com/12953598/83694047-87ad2d00-a5f7-11ea-810f-080506bc36d6.png)
We can see that the cursor is right next to the `min_freq` variable, which is, in fact, a constructor argument with a default value. But so are `max_size`, `special` and others. Yet, those are colored blue and this one is colored pinkish
![Screenshot_20200604_000503](https://user-images.githubusercontent.com/12953598/83694042-854ad300-a5f7-11ea-9583-03aef6d2dfd4.png)
Here we see that it's correctly recognized as the constructor argument, and should be colored blue.

**Comment by InCogNiTo124** [comment]
nvm figured it out

**Comment by wookayin** [comment]
Those variables in a list comprehension are "closures" and therefore are colored in magenta.
