### ISSUE TITLE
Error with highlighting

### ISSUE THREAD

**Issue by ayushchakravarthy** [numirias/semshi#91]
The highlighting doesn't work and whenever I start nvim I get the following error:
Error detected while processing BufWipeout Autocommands for "*":                                                                                                                                 
E117: Unknown function: SemshiBufWipeout
E117: Unknown function: SemshiBufWipeout

I get different errors each time I work with this plugin what do I do?

**Comment by 0xh007** [comment]
Yep, I'm no seeing this as well. Not sure if it's related, but seemed to pop up once I updated my ubuntu 20.04 server today.

**Comment by 0xh007** [comment]
Update: I reinstalled the plugin according to the readme, and it appears to be working again.

**Comment by Saul-Dickson** [comment]
I had the same problem. Go into your `~/.config/nvim/[site]/plugged/semshi` directory and run `[sudo] python setup.py install`. That should fix the problem.
